# Generated by Django 3.2.7 on 2021-10-14 05:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='simplemodel',
            old_name='venue',
            new_name='author',
        ),
    ]
