# Generated by Django 3.2.7 on 2021-10-14 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_rename_venue_simplemodel_author'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='simplemodel',
            options={'permissions': (('assign_post', 'Assign post'),)},
        ),
    ]
