# Generated by Django 3.2.7 on 2021-10-14 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_alter_simplemodel_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='simplemodel',
            options={'permissions': (('assign_post', 'Assign post'), ('view_project', 'View Posts'))},
        ),
    ]
